# Generated by Django 5.2.6 on 2025-11-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_email_verified_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium subscription status'),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, help_text='Premium subscription expiration date', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('premium', 'Premium User'), ('free', 'Free User')], default='free', help_text='User role for access control', max_length=20),
        ),
    ]
