# Generated by Django 5.2.6 on 2025-10-24 20:34

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteattachment',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='noteattachment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='noteattachment',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noteattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='noteattachment',
            name='file',
            field=models.FileField(upload_to=core.utils.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg', 'pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'mp3', 'wav', 'ogg', 'm4a', 'mp4', 'avi', 'mov', 'wmv', 'mkv', 'zip', 'rar', '7z', 'tar', 'gz'])]),
        ),
    ]
