# Generated by Django 5.2.6 on 2025-12-06 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('file_original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('pptx', 'PowerPoint Presentation'), ('txt', 'Text File'), ('csv', 'CSV File'), ('png', 'PNG Image'), ('jpg', 'JPG Image'), ('jpeg', 'JPEG Image'), ('gif', 'GIF Image'), ('zip', 'ZIP Archive')], max_length=10)),
                ('original_file_size', models.BigIntegerField(help_text='Size in bytes before compression')),
                ('compressed_file_size', models.BigIntegerField(blank=True, help_text='Actual stored size in bytes', null=True)),
                ('compression_ratio', models.FloatField(blank=True, help_text='Compression ratio (0.0 to 1.0)', null=True)),
                ('compression_algorithm', models.CharField(choices=[('zstd', 'Zstandard'), ('deflate', 'DEFLATE'), ('brotli', 'Brotli'), ('none', 'None')], default='none', max_length=10)),
                ('is_compressed', models.BooleanField(default=False)),
                ('original_file_checksum', models.CharField(help_text='SHA256 hash', max_length=64)),
                ('compressed_file_checksum', models.CharField(blank=True, help_text='SHA256 hash of compressed file', max_length=64)),
                ('compression_timestamp', models.DateTimeField(blank=True, null=True)),
                ('decompression_failed', models.BooleanField(default=False)),
                ('compression_status', models.CharField(choices=[('pending', 'Pending'), ('compressing', 'Compressing'), ('compressed', 'Compressed'), ('failed', 'Failed'), ('uncompressed', 'Uncompressed')], default='pending', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('share_expiry', models.DateTimeField(blank=True, null=True)),
                ('share_password', models.CharField(blank=True, max_length=128)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('access_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_file', models.FileField(upload_to='backups/%Y/%m/%d/')),
                ('backup_created', models.DateTimeField(auto_now_add=True)),
                ('backup_expires', models.DateTimeField()),
                ('is_used_for_recovery', models.BooleanField(default=False)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup', to='documents.document')),
            ],
            options={
                'ordering': ['-backup_created'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(default='folder', help_text='Icon name', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory'),
        ),
        migrations.CreateModel(
            name='DocumentShareLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_method', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('direct_link', 'Direct Link'), ('internal_user', 'Internal User')], max_length=20)),
                ('recipient', models.CharField(help_text='Email, phone, or username', max_length=255)),
                ('recipient_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('user', 'User')], max_length=10)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('opened', 'Opened')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_logs', to='documents.document')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Document Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.documenttag'),
        ),
        migrations.CreateModel(
            name='UserStorageQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_quota', models.BigIntegerField(default=1099511627776, help_text='Allowed storage in bytes')),
                ('original_used', models.BigIntegerField(default=0, help_text='Sum of original file sizes')),
                ('compressed_used', models.BigIntegerField(default=0, help_text='Actual disk usage')),
                ('compression_savings', models.BigIntegerField(default=0, help_text='Bytes saved by compression')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('document_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Storage Quotas',
            },
        ),
        migrations.CreateModel(
            name='CompressionStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('pptx', 'PowerPoint Presentation'), ('txt', 'Text File'), ('csv', 'CSV File'), ('png', 'PNG Image'), ('jpg', 'JPG Image'), ('jpeg', 'JPEG Image'), ('gif', 'GIF Image'), ('zip', 'ZIP Archive')], max_length=10)),
                ('algorithm', models.CharField(choices=[('zstd', 'Zstandard'), ('deflate', 'DEFLATE'), ('brotli', 'Brotli'), ('none', 'None')], max_length=10)),
                ('total_files', models.IntegerField(default=0)),
                ('avg_compression_ratio', models.FloatField(default=0.0)),
                ('total_original_size', models.BigIntegerField(default=0)),
                ('total_compressed_size', models.BigIntegerField(default=0)),
                ('avg_compression_time', models.FloatField(default=0.0, help_text='Average compression time in milliseconds')),
                ('failure_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compression_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Compression Statistics',
                'indexes': [models.Index(fields=['user', 'file_type'], name='documents_c_user_id_7c396a_idx'), models.Index(fields=['user', 'algorithm'], name='documents_c_user_id_db2ca5_idx')],
                'unique_together': {('user', 'file_type', 'algorithm')},
            },
        ),
        migrations.AddIndex(
            model_name='documentcategory',
            index=models.Index(fields=['user', 'created_at'], name='documents_d_user_id_090f55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentcategory',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='documentsharelog',
            index=models.Index(fields=['document', '-shared_at'], name='documents_d_documen_7d7c56_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsharelog',
            index=models.Index(fields=['shared_by', '-shared_at'], name='documents_d_shared__ba5614_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsharelog',
            index=models.Index(fields=['recipient', 'status'], name='documents_d_recipie_e9bc27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttag',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', '-upload_date'], name='documents_d_user_id_34f5ce_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'category'], name='documents_d_user_id_d6b7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'is_favorite'], name='documents_d_user_id_d059ba_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'compression_status'], name='documents_d_user_id_8b84b4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['share_token'], name='documents_d_share_t_b7205e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'file_type'], name='documents_d_user_id_7b2a85_idx'),
        ),
    ]
