# Generated by Django 5.2.6 on 2025-12-09 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['name'], 'verbose_name': 'Folder', 'verbose_name_plural': 'Folders'},
        ),
        migrations.AlterUniqueTogether(
            name='documentcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='depth',
            field=models.PositiveIntegerField(default=0, help_text='Nesting depth level'),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='documents.documentcategory'),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='path',
            field=models.CharField(blank=True, help_text='Cached full path', max_length=1000),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory', verbose_name='Folder'),
        ),
        migrations.AlterUniqueTogether(
            name='documentcategory',
            unique_together={('user', 'name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='documentcategory',
            index=models.Index(fields=['user', 'parent'], name='documents_d_user_id_7074d4_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcategory',
            index=models.Index(fields=['user', 'path'], name='documents_d_user_id_225b0d_idx'),
        ),
    ]
