# Generated by Django 5.2.6 on 2025-12-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultsession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of unlock', null=True),
        ),
        migrations.AlterField(
            model_name='vaultsession',
            name='user_agent',
            field=models.CharField(blank=True, default='', help_text='User agent string', max_length=255),
        ),
    ]
